### ISSUE TITLE
Import type with csv

### ISSUE THREAD

**Issue by yakattack1** [djamp42/csv2librenms#3]
Thanks for the great script.  I imported a group of "ping" devices but they have no type associated with them (e.g. wireless).  
Wondering if we can add the type to the script.  I'm new to API and Python.

I tried adding
            # Update device with type if provided
            if math.isnan(row['type']):
                pass
            else:
                type = {"field": ["type"],
                            "data": [row['type']]
                            }
                device_update(row['hostname'], type)

But received a lot of errors:

config-w-type.py", line 69, in <module>
    if math.isnan(row['type']):
TypeError: must be real number, not str

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python\lib\site-packages\requests\models.py", line 473, in prepare_body
    body = complexjson.dumps(json, allow_nan=False)
  File "C:\Python\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Python\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
ValueError: Out of range float values are not JSON compliant

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Downloads/csv2librenms-master/config-w-type.py", line 84, in <module>
    device_add(add_device)
  File "C:/Downloads/csv2librenms-master/config-w-type.py", line 18, in device_add
    r = requests.post(api_url, json=add_request, headers=request_headers)
  File "C:\Python\lib\site-packages\requests\api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Python\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python\lib\site-packages\requests\sessions.py", line 515, in request
    prep = self.prepare_request(req)
  File "C:\Python\lib\site-packages\requests\sessions.py", line 443, in prepare_request
    p.prepare(
  File "C:\Python\lib\site-packages\requests\models.py", line 321, in prepare
    self.prepare_body(data, files, json)
  File "C:\Python\lib\site-packages\requests\models.py", line 475, in prepare_body
    raise InvalidJSONError(ve, request=self)
requests.exceptions.InvalidJSONError: Out of range float values are not JSON compliant

**Comment by yakattack1** [comment]
One issue is that type is a python command so I changed the variable to Type.  Now different errors.

**Comment by yakattack1** [comment]
Got it working:

            # Update device with type if provided
            # if math.isnan(row['type']):
            #    pass
            # else:
                Type = {"field": ["type"],
                            "data": [row['type']]
                            }
                device_update(row['hostname'], Type)
